### ISSUE TITLE
Pantry Hours: Alter input to fit their new format

### ISSUE THREAD

**Issue by jschnapper** [CalNourish/ucbfpa-webapp#94]
Pantry hours have a new format:

![image](https://user-images.githubusercontent.com/15844781/64306357-7fd53500-cf60-11e9-994c-92990c652747.png)

**Comment by jschnapper** [comment]
Make hours similar to when2meet

**Comment by samanthalai0914** [comment]
assuming that the hours schema will need to be changed, we should put the new hours info under an hours table within info

-barcodes
-info
    - hours
        - [NEW HOURS INFO HERE]
    - restock
        - produce
        - bread
        - etc
-inventory
-etc
